/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSetsRouteImport } from './routes/api/sets'
import { Route as ApiCardsRouteImport } from './routes/api/cards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetsRoute = ApiSetsRouteImport.update({
  id: '/api/sets',
  path: '/api/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsRoute = ApiCardsRouteImport.update({
  id: '/api/cards',
  path: '/api/cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/sets': typeof ApiSetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/sets': typeof ApiSetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/sets': typeof ApiSetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cards' | '/api/sets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cards' | '/api/sets'
  id: '__root__' | '/' | '/api/cards' | '/api/sets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCardsRoute: typeof ApiCardsRoute
  ApiSetsRoute: typeof ApiSetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sets': {
      id: '/api/sets'
      path: '/api/sets'
      fullPath: '/api/sets'
      preLoaderRoute: typeof ApiSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards': {
      id: '/api/cards'
      path: '/api/cards'
      fullPath: '/api/cards'
      preLoaderRoute: typeof ApiCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCardsRoute: ApiCardsRoute,
  ApiSetsRoute: ApiSetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
